In [32]:
import pandas as pd

In [33]:
data = pd.read_csv('../data/new_cars_dataset_2.csv')
data.head()

C:\Users\Дмитро\AppData\Local\Temp\ipykernel_47664\617072621.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('../data/new_cars_dataset_2.csv')

,ID,Mark,MarkId,Model,ModelId,Modification,CategoryId,Price_USD,Price_UAH,Price_EUR,...,Main_Photo_URL,Main_Photo_Path,Photos_Count,With_Video,Description_Length,Options_Count,Desc_Urgent,Desc_Bargain,Desc_First_Owner,Desc_Ideal
0,40427785,Peugeot,58,307,526,NaN,1,3800,170278,3272,...,https://cdn4.riastatic.com/photosnew/auto/phot...,NaN,3,False,0,0,False,False,False,False
1,40427759,BMW,9,X3,1866,NaN,1,29985,1343627,25809,...,https://cdn3.riastatic.com/photosnew/auto/phot...,NaN,25,False,0,0,False,False,False,False
2,40427740,Audi,6,A5,2032,NaN,1,30999,1388755,26701,...,https://cdn4.riastatic.com/photosnew/auto/phot...,NaN,17,False,0,0,False,False,False,False
3,40427705,Jeep,32,Compass,2842,NaN,1,16000,716960,13777,...,https://cdn0.riastatic.com/photosnew/auto/phot...,NaN,15,False,0,0,False,False,False,False
4,40427621,Toyota,79,Land Cruiser,35000,NaN,1,26500,1187200,22826,...,https://cdn3.riastatic.com/photosnew/auto/phot...,NaN,70,False,0,0,False,False,False,False

In [34]:
data.columns

Index(['ID', 'Mark', 'MarkId', 'Model', 'ModelId', 'Modification',
       'CategoryId', 'Price_USD', 'Price_UAH', 'Price_EUR', 'Main_Currency',
       'Auction_Possible', 'Year', 'Age', 'Mileage_K', 'Mileage_Per_Year',
       'Engine_Volume', 'Fuel_Name', 'Fuel_Id', 'Gearbox_Name', 'Gearbox_Id',
       'Body_Name', 'Body_Id', 'Color_Name', 'Color_Id', 'Drive_Name',
       'Drive_Id', 'Wheel_Name', 'SeatsNumber', 'DoorsNumber', 'Custom',
       'Country_Origin_Id', 'ConditionId', 'StatusId', 'Is_Crashed',
       'Damage_Description', 'Is_Leasing', 'Has_VIN', 'Is_Checked_VIN', 'VIN',
       'VIN_Has_Restrictions', 'Has_Plate', 'Is_Checked_Plate', 'State_Id',
       'State_Name', 'City_Id', 'City', 'UserId', 'Is_Dealer', 'PartnerId',
       'Dealer_Name', 'Seller_Type', 'Phone_Verified', 'Exchange_Possible',
       'Exchange_Type', 'Add_Date', 'Update_Date', 'Expire_Date', 'Is_Sold',
       'From_Archive', 'On_Moderation', 'Views_Total', 'Views_Today',
       'Bookmarks_Count', 'Chips_Count', 'Top_Level', 'Top_Label', 'Hot_Type',
       'Badges_Count', 'Ad_Link', 'Main_Photo_URL', 'Main_Photo_Path',
       'Photos_Count', 'With_Video', 'Description_Length', 'Options_Count',
       'Desc_Urgent', 'Desc_Bargain', 'Desc_First_Owner', 'Desc_Ideal'],
      dtype='object')

In [35]:
data[['ID', 'Mark',  'Model', 'Year', 'Price_USD', 'Mileage_K','Fuel_Name', 'Gearbox_Name']].head()

,ID,Mark,Model,Year,Price_USD,Mileage_K,Fuel_Name,Gearbox_Name
0,40427785,Peugeot,307,2005,3800,160,Бензин,Ручна / Механіка
1,40427759,BMW,X3,2021,29985,79,"Бензин, 2 л.",Автомат
2,40427740,Audi,A5,2020,30999,67,"Бензин, 1.98 л.",Автомат
3,40427705,Jeep,Compass,2019,16000,86,"Газ пропан-бутан / Бензин, 2.36 л.",Автомат
4,40427621,Toyota,Land Cruiser,2011,26500,300,"Дизель, 4.5 л.",Автомат

['ID', 'Mark', 'Model', 'Year', 'Price_USD', 'Mileage', 'Engine', 'Fuel', 'Gearbox']
- "['Mileage', 'Engine', 'Fuel', 'Gearbox'] not in index"

In [36]:
data.rename(columns={"Mileage_K": "Mileage", "Fuel_Name": "Fuel", "Gearbox_Name":'Gearbox'}, inplace=True)

In [38]:
clean_data = data[['ID', 'Mark',  'Model', 'Year', 'Price_USD', 'Mileage','Fuel', 'Gearbox']].head(20000)

In [39]:
clean_data.to_csv('../data/new_clean_data_twenty.csv')